const fs = require('fs');

const entries = JSON.parse(fs.readFileSync('data/entries.json', 'utf8'));

// Comprehensive Indonesian translation mapping
const translationMap = {
  // architectural-terms-theory
  "axis": "sumbu",
  "balance": "keseimbangan",
  "proportion": "proporsi",
  "composition": "komposisi",
  "focal-point": "titik fokus",
  "emphasis": "penekanan",
  "space": "ruang",
  "form": "bentuk",
  "unity": "kesatuan",
  "harmony": "harmoni",
  "pattern": "pola",
  "rhythm": "ritme",
  "sequence": "sekuens",
  "symmetry": "simetri",
  "asymmetry": "asimetri",
  "hierarchy": "hierarki",
  "rhythm": "ritme",
  "contrast": "kontras",
  "figure-ground": "figur-latar",
  "modularity": "modularitas",
  "fenestration": "fenestrasi",
  "articulation": "artikulasi",
  "porosity": "porositas",
  "layering": "berlapis",
  "threshold": "ambang batas",
  "figure-field": "figur-medan",
  "datum": "datum",
  "gestalt": "gestalt",
  "void": "ruang kosong",
  "connection": "koneksi",
  "fenestration-pattern": "pola fenestrasi",
  "circulation": "sirkulasi",
  "materiality": "materialitas",
  "context": "konteks",
  "spatial-sequence": "sekuens spasial",
  "mezzanine": "mezzanine",

  // building-materials-construction
  "concrete": "beton",
  "steel": "baja",
  "brick": "bata",
  "wood": "kayu",
  "glass": "kaca",
  "stone": "batu",
  "tile": "ubin",
  "plaster": "plester",
  "mortar": "adukan",
  "cement": "semen",
  "aggregate": "agregat",
  "reinforced-concrete": "beton bertulang",
  "prestressed-concrete": "beton pratekan",
  "masonry": "batu bata/material massa",
  "timber-frame": "rangka kayu",
  "prefabrication": "prefabrikasi",
  "casting": "pengecoran",
  "formwork": "bekisting",
  "curing": "pengerasan",
  "joinery": "penyambungan",
  "bolt": "baut",
  "fastener": "pengikat",
  "half-timber": "rangka kayu setengah",
  "asphalt": "aspal",
  "aluminum": "aluminium",
  "composite-material": "material komposit",
  "gypsum": "gipsum",
  "mineral-wool": "wol mineral",
  "fiberglass": "serat kaca",
  "polycarbonate": "polikarbonat",
  "brick-veneer": "kulit bata",
  "waterproofing": "waterproofing",
  "damp-proofing": "damp-proofing",
  "sealant": "sealant",
  "paint": "cat",
  "insulation": "insulasi",
  "rebar": "besi tulangan",

  // structural-systems
  "arch": "lengkung",
  "barrel-vault": "vault silinder",
  "beam": "balok",
  "bearing-wall": "dinding penahan",
  "bracing": "pengaku",
  "buttress": "pilar penunjang",
  "cable-stayed": "kabel tinggal",
  "compression": "kompresi",
  "dome": "kubah",
  "ductility": "keuletan",
  "elastic": "elastis",
  "flying-buttress": "pilar penunjang terbang",
  "force": "gaya",
  "foundation": "fondasi",
  "frame": "rangka",
  "inflection": "infleksi",
  "joist": "balok miring",
  "lateral-system": "sistem lateral",
  "load-bearing": "penahan beban",
  "moment-frame": "rangka momen",
  "post-and-beam": "tiang dan balok",
  "shear-wall": "dinding geser",
  "tension": "tegangan",
  "torsion": "puntir",
  "shear": "geser",
  "cable-structure": "struktur kabel",
  "truss": "rangka kuda-kuda",
  "cantilever": "kantilever",

  // design-styles-movements
  "modernism": "modernisme",
  "postmodernism": "postmodernisme",
  "baroque": "barok",
  "gothic": "gotik",
  "renaissance": "renaisans",
  "neoclassical": "neoklasik",
  "art-deco": "art-deco",
  "art-nouveau": "art-nouveau",
  "art-and-crafts": "seni dan kerajinan",
  "streamline-moderne": "streamline-moderne",
  "international-style": "gaya internasional",
  "functionalism": "fungsionalisme",
  "constructivism": "konstruktivisme",
  "suprematism": "suprematisme",
  "futurism": "futurisme",
  "expressionism": "ekspresionisme",
  "regionalism": "regionalisme",
  "organic-architecture": "arsitektur organik",
  "vernacular": "vernakular",
  "minimalism": "minimalisme",
  "contemporary": "kontemporer",
  "rationalism": "rasionalisme",
  "critical-regionalism": "regionalisme kritis",
  "metabolism": "metabolisme",
  "brutalism": "brutalisme",
  "high-tech": "high-tech",
  "vernacular-revival": "kebangkitan vernakular",
  "neoeclecticism": "neoeklektisisme",
  "minimal-architecture": "arsitektur minimal",
  "deconstructivism": "dekonstruktivisme",

  // tools-software-technology
  "bim": "bim",
  "cad": "cad",
  "revit": "revit",
  "autocad": "autocad",
  "sketchup": "sketchup",
  "grasshopper": "grasshopper",
  "rhino": "rhino",
  "dynamo": "dynamo",
  "unreal-engine": "unreal-engine",
  "unity": "unity",
  "vr": "vr",
  "virtual-reality": "realitas virtual",
  "rendering": "rendering",
  "3d-modeling": "pemodelan 3d",
  "parametric-design": "desain parametrik",
  "digital-design": "desain digital",
  "laser-scanning": "pemindaian laser",
  "photogrammetry": "fotogrametri",
  "computational-design": "desain komputasional",
  "visual-programming": "pemrograman visual",
  "algorithm": "algoritma",
  "augmented-reality": "augmented-reality",
  "artificial-intelligence": "kecerdasan buatan",
  "point-cloud": "cloud poin",
  "cloud-computing": "cloud-computing",
  "api": "api",
  "artificial-photosynthesis": "generative-design",
  "json": "json",
  "real-time-rendering": "rendering real-time",
  "mesh": "mesh",
  "node-based-design": "desain berbasis node",

  // sustainability
  "green-building": "bangunan hijau",
  "leed": "leed",
  "passive-design": "desain pasif",
  "renewable-energy": "energi terbarukan",
  "solar-energy": "energi surya",
  "wind-energy": "energi angin",
  "geothermal": "geotermal",
  "biomass": "biomassa",
  "recycling": "daur ulang",
  "water-management": "manajemen air",
  "rainwater-harvesting": "panen air hujan",
  "greywater": "air abu-abu",
  "energy-efficiency": "efisiensi energi",
  "hvac": "hvac",
  "building-automation": "otomasi bangunan",
  "green-roof": "atap hijau",
  "green-wall": "dinding hijau",
  "biodiversity": "keanekaragaman hayati",
  "carbon-footprint": "jejak karbon",
  "lifecycle-assessment": "penilaian daur hidup",
  "net-zero": "net-zero",
  "embodied-carbon": "karbon tersimpan",
  "biomimicry": "biomimikri",

  // codes-standards
  "building-code": "kode bangunan",
  "accessibility-standards": "standar aksesibilitas",
  "energy-code": "kode energi",
  "fire-code": "kode kebakaran",
  "zoning-ordinance": "ordinansi zonasi",
  "certification-standards": "standar sertifikasi",

  // urban-design
  "public-space": "ruang publik",
  "plaza": "plaza",
  "street": "jalan",
  "waterfront": "tepi air",
  "walkability": "keterjangkauan jalan kaki",
  "zoning": "zonasi",
  "mixed-use": "campuran guna",
  "density": "kepadatan",
  "public-transit": "transit publik",
  "block": "blok",
  "node": "simpul",
  "permeable": "permeabel",
  "landmark": "landmark",
  "place-making": "pembuatan tempat",
  "edge": "tepi",
  "infill-development": "pengembangan isian",
  "accessibility": "aksesibilitas",
  "placemaking": "pembuatan tempat",
  "third-place": "tempat ketiga",
  "gentrification": "gentrifikasi",
  "new-urbanism": "new-urbanism",
  "tactical-urbanism": "urban taktis",

  // key-figures
  "frank-lloyd-wright": "frank-lloyd-wright",
  "le-corbusier": "le-corbusier",
  "zaha-hadid": "zaha-hadid",
  "i-m-pei": "i-m-pei",
  "louis-kahn": "louis-kahn",
  "rem-koolhaas": "rem-koolhaas",
  "norma-merrick-sklarek": "norma-merrick-sklarek",
  "alvar-aalto": "alvar-aalto",
  "david-chipperfield": "david-chipperfield",
  "maya-lin": "maya-lin",
  "brasilia-lucio-costa": "lúcio-costa",
  "oscar-niemeyer": "oscar-niemeyer",
  "kenzo-tange": "kenzo-tange",
  "richard-meier": "richard-meier",
  "thomas-heatherwick": "thomas-heatherwick",

  // geometry-mathematics
  "angle": "sudut",
  "arc": "busur",
  "circle": "lingkaran",
  "cone": "kerucut",
  "cylinder": "silinder",
  "diagonal": "diagonal",
  "ellipse": "elips",
  "fibonacci-sequence": "deret fibonacci",
  "fractal": "fraktal",
  "geometry": "geometri",
  "golden-ratio": "rasio emas",
  "grid": "kisi",
  "line": "garis",
  "module": "modul",
  "polygon": "poligon",
  "hyperbolic-paraboloid": "paraboloid hiperbolik",
  "hexagon": "heksagon",
  "sine-wave": "gelombang sinus",

  // building-history-typologies
  "house": "rumah",
  "villa": "villa",
  "palace": "istana",
  "castle": "kastil",
  "temple": "candi",
  "mosque": "masjid",
  "church": "gereja",
  "cathedral": "katedral",
  "basilica": "basilika",
  "synagogue": "sinagog",
  "pagoda": "pagoda",
  "monastery": "biara",
  "convent": "konven",
  "chapel": "kapel",
  "fortress": "benteng",
  "tower": "menara",
  "bridge": "jembatan",
  "aqueduct": "saluran air",
  "amphitheater": "amphitheater",
  "theater": "teater",
  "stadium": "stadion",
  "market": "pasar",
  "warehouse": "gudang",
  "factory": "pabrik",
  "office": "kantor",
  "school": "sekolah",
  "hospital": "rumah sakit",
  "library": "perpustakaan",
  "museum": "museum",
  "hotel": "hotel",
  "restaurant": "restoran",
  "bank": "bank",

  // architecture-across-cultures
  "chinese-architecture": "arsitektur china",
  "japanese-architecture": "arsitektur jepang",
  "indian-architecture": "arsitektur india",
  "islamic-architecture": "arsitektur islam",
  "african-architecture": "arsitektur africa",
  "asian": "asia",
  "european": "eropa",
  "americas": "benua amerika",
  "vernacular": "vernakular",
  "indigenous": "asli",
  "traditional": "tradisional",
  "ancient": "kuno",
  "classical": "klasik",
  "medieval": "abad pertengahan",
  "colonial": "kolonial",
  "modern": "modern",
  "contemporary": "kontemporer",

  // professional-practice
  "architect": "arsitek",
  "award": "penghargaan",
  "brief": "arahan singkat",
  "client": "klien",
  "collaboration": "kolaborasi",
  "competition": "kompetisi",
  "construction-management": "manajemen konstruksi",
  "consultant": "konsultan",
  "contract": "kontrak",
  "contractor": "kontraktor",
  "coordination": "koordinasi",
  "developer": "pengembang",
  "design-development": "pengembangan desain",
  "fees": "biaya",
  "licensing": "lisensi",
  "precedent": "preseden",
  "program": "program",
  "cad": "cad",
  "design-thinking": "desain berpikir",
  "precedent-study": "studi preseden",

  // building-performance-physics
  "acoustics": "akustik",
  "air-infiltration": "infiltrasi udara",
  "air-quality": "kualitas udara",
  "daylighting": "pencahayaan alami",
  "glare": "silau",
  "humidity": "kelembaban",
  "light-shelf": "rak cahaya",
  "thermal-bridge": "jembatan panas",
  "thermal-comfort": "kenyamanan termal",
  "ventilation": "ventilasi",
  "visible-light-transmission": "transmisi cahaya tampak",
  "ductility": "keuletan",
  "thermal-mass": "massa termal",
  "thermal-resistance": "resistansi panas",
  "solar-gain": "penambahan solar",
  "sound-transmission": "transmisi suara",
  "decibel": "desibel",
  "air-tightness": "ketautan udara",

  // representation-communication
  "drawing": "gambar",
  "plan": "denah",
  "elevation": "tampak",
  "model": "model",
  "rendering": "rendering",
  "sketch": "sketsa",
  "diagram": "diagram",
  "section": "potongan",
  "perspective-drawing": "gambar perspektif",
  "isometric-drawing": "gambar isometrik",
  "section-drawing": "gambar potongan",
  "axonometric": "aksonometrik",

  // Additional translations
  "passive-design": "desain pasif",
  "natural-light": "cahaya alami",
  "window": "jendela",
  "health": "kesehatan",
  "indoor-environment": "lingkungan dalam ruangan",
  "natural": "alami",
  "view": "pandangan",
  "outdoor": "luar ruangan",
  "open-space": "ruang terbuka",
  "interior": "interior",
  "exterior": "exterior",
  "facade": "fasad",
  "roof": "atap",
  "floor": "lantai",
  "wall": "dinding",
  "column": "kolom",
  "beam": "balok",
  "stair": "tangga",
  "door": "pintu",
  "opening": "bukaan",
  "level": "tingkat",
  "floor-plan": "denah lantai",
  "spatial-composition": "komposisi spasial",
  "perception": "persepsi",
  "experience": "pengalaman",
  "movement": "gerakan",
  "color": "warna",
  "material": "material",
  "texture": "tekstur",
  "detail": "detail",
  "assembly": "perakitan",
  "joint": "sambungan",
  "light": "cahaya",
  "shadow": "bayangan",
  "transparency": "transparansi",
  "opacity": "opasitas",
  "reflection": "refleksi",
  "sound": "suara",
  "noise": "kebisingan",
  "silence": "keheningan",
  "privacy": "privasi",
  "security": "keamanan",
  "comfort": "kenyamanan",
  "safety": "keselamatan",
  "accessibility": "aksesibilitas",
  "flexibility": "fleksibilitas",
  "sustainability": "keberlanjutan",
  "durability": "daya tahan",
  "maintenance": "pemeliharaan",
  "cost": "biaya",
  "budget": "anggaran",
  "schedule": "jadwal",
  "timeline": "garis waktu",
  "design-process": "proses desain",
  "research": "penelitian",
  "analysis": "analisis",
  "conceptualization": "konseptualisasi",
  "ideation": "ideasi",
  "sketch": "sketsa",
  "presentation": "presentasi",
  "approval": "persetujuan",
  "construction": "konstruksi",
  "completion": "penyelesaian",
  "occupancy": "hunian",
  "operation": "operasional",
  "maintenance": "pemeliharaan",
  "adaptation": "adaptasi",
  "renovation": "renovasi",
  "restoration": "restorasi",
  "preservation": "preservasi",
  "heritage": "warisan",
  "conservation": "konservasi",
  "regulation": "regulasi",
  "policy": "kebijakan",
  "building-system": "sistem bangunan",
  "structure": "struktur",
  "envelope": "kulit bangunan",
  "interior-design": "desain interior",
  "landscape-design": "desain lanskap",
  "urban-design": "desain urban",
  "master-plan": "rencana induk",
  "site-plan": "denah situs",
  "landscape": "lanskap",
  "site": "situs",
  "location": "lokasi",
  "neighborhood": "lingkungan",
  "district": "distrik",
  "city": "kota",
  "region": "wilayah",
  "climate": "iklim",
  "weather": "cuaca",
  "environment": "lingkungan",
  "nature": "alam",
  "ecology": "ekologi",
  "ecology": "ekologi",
  "sustainable": "berkelanjutan",
  "green": "hijau",
  "eco-friendly": "ramah lingkungan",
  "low-carbon": "rendah karbon",
  "efficiency": "efisiensi",
  "performance": "kinerja",
  "optimization": "optimisasi",
  "analysis": "analisis",
  "simulation": "simulasi",
  "monitoring": "pemantauan",
  "measurement": "pengukuran",
  "evaluation": "evaluasi",
  "improvement": "perbaikan",
  "innovation": "inovasi",
  "technology": "teknologi",
  "digital": "digital",
  "computational": "komputasional",
  "automation": "otomasi",
  "integration": "integrasi",
  "data": "data",
  "information": "informasi",
  "communication": "komunikasi",
  "collaboration": "kolaborasi",
  "teamwork": "kerja tim",
  "coordination": "koordinasi",
  "management": "manajemen",
  "administration": "administrasi",
  "organization": "organisasi",
  "planning": "perencanaan",
  "strategy": "strategi",
  "vision": "visi",
  "mission": "misi",
  "goal": "tujuan",
  "objective": "objektif",
  "requirement": "persyaratan",
  "constraint": "batasan",
  "parameter": "parameter",
  "variable": "variabel",
  "constant": "konstanta",
  "ratio": "rasio",
  "scale": "skala",
  "dimension": "dimensi",
  "measurement": "pengukuran",
  "unit": "unit",
  "metric": "metrik",
  "standard": "standar",
  "specification": "spesifikasi",
  "documentation": "dokumentasi",
  "drawing": "gambar",
  "annotation": "anotasi",
  "notation": "notasi",
  "symbol": "simbol",
  "legend": "legenda",
  "scale": "skala",
  "orientation": "orientasi",
  "direction": "arah",
  "north": "utara",
  "south": "selatan",
  "east": "timur",
  "west": "barat",
  "depth": "kedalaman",
  "height": "tinggi",
  "width": "lebar",
  "length": "panjang",
  "area": "luas",
  "volume": "volume",
  "mass": "massa",
  "weight": "berat",
  "density": "kepadatan",
  "gravity": "gravitasi",
  "load": "beban",
  "stress": "tegangan",
  "strain": "regangan",
  "deformation": "deformasi",
  "deflection": "defleksi",
  "movement": "gerakan",
  "vibration": "getaran",
  "oscillation": "osilasi",
  "frequency": "frekuensi",
  "wavelength": "panjang gelombang",
  "amplitude": "amplitudo",
  "phase": "fase",
  "resonance": "resonansi",
  "damping": "redaman",
  "stiffness": "kekakuan",
  "flexibility": "fleksibilitas",
  "resilience": "resiliensi",
  "brittleness": "kerapuhan",
  "malleability": "kelenturan",
  "hardness": "kekerasan",
  "softness": "kelunakan",
  "durability": "daya tahan",
  "degradation": "degradasi",
  "deterioration": "deteriorasi",
  "aging": "penuaan",
  "patina": "patina",
  "corrosion": "korosi",
  "rust": "karat",
  "moisture": "kelembaban",
  "water": "air",
  "drainage": "drainase",
  "seepage": "rembesan",
  "erosion": "erosi",
  "weathering": "pelapukan",
  "freeze-thaw": "beku-pencairan",
  "thermal-expansion": "ekspansi termal",
  "contraction": "kontraksi",
  "shrinkage": "penyusutan",
  "swelling": "pembengkakan",
  "cracking": "retak",
  "settlement": "penurunan",
  "subsidence": "subsiden",
  "heave": "pengangkatan",
  "buckling": "tekuk",
  "warping": "melengkung",
  "twisting": "puntiran",
  "splitting": "pemisahan",
  "delamination": "delaminasi",
  "spalling": "spalling",
  "erosion": "erosi",
  "abrasion": "abrasi",
  "impact": "dampak",
  "collision": "tabrakan",
  "vibration": "getaran",
  "fatigue": "kelelahan",
  "creep": "creep",
  "relaxation": "relaksasi",
  "strength": "kekuatan",
  "weakness": "kelemahan",
  "failure": "kegagalan",
  "collapse": "keruntuhan",
  "disaster": "bencana",
  "emergency": "darurat",
  "evacuation": "evakuasi",
  "refuge": "perlindungan",
  "shelter": "tempat berlindung",
  "escape": "jalan keluar",
  "exit": "pintu keluar",
  "entrance": "pintu masuk",
  "access": "akses",
  "egress": "keluar",
  "way-finding": "pencarian jalan",
  "signage": "penandaan",
  "wayfinding": "pencarian jalan",
  "navigation": "navigasi",
  "orientation": "orientasi",
  "legibility": "keterbacaan",
  "clarity": "kejelasan",
  "visibility": "visibilitas",
  "recognition": "pengenalan",
  "identity": "identitas",
  "character": "karakter",
  "personality": "kepribadian",
  "authenticity": "keaslian",
  "integrity": "integritas",
  "wholeness": "kebulatan",
  "coherence": "koherensi",
  "consistency": "konsistensi",
  "continuity": "kontinuitas",
  "connection": "koneksi",
  "relationship": "hubungan",
  "interaction": "interaksi",
  "engagement": "keterlibatan",
  "participation": "partisipasi",
  "community": "komunitas",
  "society": "masyarakat",
  "culture": "budaya",
  "tradition": "tradisi",
  "custom": "kebiasaan",
  "convention": "konvensi",
  "norm": "norma",
  "value": "nilai",
  "belief": "kepercayaan",
  "meaning": "makna",
  "symbolism": "simbolisme",
  "metaphor": "metafora",
  "narrative": "narasi",
  "story": "cerita",
  "history": "sejarah",
  "past": "masa lalu",
  "present": "saat ini",
  "future": "masa depan",
  "time": "waktu",
  "era": "era",
  "period": "periode",
  "epoch": "zaman",
  "age": "usia",
  "generation": "generasi",
  "legacy": "warisan",
};

// Add indonesianTerm to each entry
const updatedEntries = entries.map(entry => {
  const indonesianTerm = translationMap[entry.id];
  if (indonesianTerm) {
    return { ...entry, indonesianTerm };
  }
  return entry;
});

// Write back to file
fs.writeFileSync('data/entries.json', JSON.stringify(updatedEntries, null, 2) + '\n');

console.log(`Updated ${updatedEntries.filter(e => e.indonesianTerm).length} entries with Indonesian terms`);
console.log(`Total entries: ${updatedEntries.length}`);

// Show entries without Indonesian terms
const missingTranslations = updatedEntries.filter(e => !e.indonesianTerm);
if (missingTranslations.length > 0) {
  console.log(`\nMissing translations for ${missingTranslations.length} entries:`);
  missingTranslations.forEach(e => {
    console.log(`  "${e.id}": "${e.term}",`);
  });
}
